### ISSUE TITLE
How to import it?

### ISSUE THREAD

**Issue by dz-root** [mrmikardo/svelte-hcaptcha#12]
Hey! After installing it, I'm little a bit confused the way I can import it
Is it the good way to import it : `import HCaptcha from 'svelte-hcaptcha'`

**Comment by mrmikardo** [comment]
Hey @dz-root, that should work! Could you share a code snippet of what you're trying to do? I haven't looked at this repo in a while, it's possible something has fallen off...

**Comment by dz-root** [comment]
@mrmikardo every thing okay! Thank you for your prompt answare 
I had a bad public key that's why I couldn't see the Hcaptcha frame in the front side.

But whene i import it (`import HCaptcha from 'svelte-hcaptcha'`) this way, I have this error on VsCode

> Could not find a declaration file for module 'svelte-hcaptcha'. 'path/to/my-project/node_modules/svelte-hcaptcha/dist/index.js' implicitly has an 'any' type.
> Try `npm i --save-dev @types/svelte-hcaptcha` if it exists or add a new declaration (.d.ts) file containing `declare module 'svelte-hcaptcha';

**Comment by mrmikardo** [comment]
@dz-root ah, that'll be because there aren't types or a declaration file for this. So that's "not a bug, but a feature".

I'd like to implement that and will look into it this weekend if I can find time 🙂

**Comment by dz-root** [comment]
Awesome thank you! btw the current version is working very well

**Comment by mrmikardo** [comment]
@dz-root thank you! It's a pleasure to hear 😸
