### ISSUE TITLE
Add localhost warning in the README

### ISSUE THREAD

**Issue by IsAvaible** [mrmikardo/svelte-hcaptcha#7]
HCaptcha does not work over localhost. This could be a common source of errors for users who see this package as a plug and play alternative and therefore do not read the HCaptcha documentation beforehand. I suggest to add a note to test the program over 127.0.0.1 in the README.

**Comment by mrmikardo** [comment]
Hi @IsAvaible - thanks for opening this issue.

I agree that this point should be clearer on the README, and will endeavour to update soon - there are a couple of other things which are ambiguous, too, as well as a few points that need to be added since the latest changes in #3.

**Comment by mrmikardo** [comment]
I've (finally!) added this warning https://github.com/mrmikardo/svelte-hcaptcha/commit/82a4d419ce809b4b48b12619b84c6379b51628d6.
